#!/usr/bin/env bash
# Enhanced pbcopy/pbpaste, optional buffer tag as single argument

[ "$MPBDIR" ] || MPBDIR="$HOME/.mpb"

# Sanitize tag for shell, allow dashes if not in front
MPBTAG=$(echo "${2//[^a-zA-Z0-9_.-]/}" | sed 's/^-*//')

function usage() {
  [ "$*" ] && echo "Oops: $*" 1>&2
  echo "Usage: $0 <verb> [tag]
  c[opy] [tag]   - pbcopy with optional storage
  p[aste] [tag]  - pbpaste with optional storage
  s[tore] <tag>  - put contents of buffer in storage
  g[imme] <tag>  - retrieve named storage into buffer
  l[ist]         - show tags
  e[dit] [tag]   - edit the tag, or just populate an unnamed buffer
  d[elete] <tag> - you get the idea" 1>&2
  exit 1
}

# Create dir to save stuff
if [ ! -d $MPBDIR ]
then
  mkdir -p $MPBDIR
  chmod 0700 $MPBDIR
fi
cd "$MPBDIR"

# Let's do this
case "$1" in

  c*) # COPY
    pbcopy
    if [ "$MPBTAG" ]
    then
      [ -f "$MPBTAG" ] cp -pv "$MPBTAG" /tmp # safety
      pbpaste > "$MPBTAG"
    fi
  ;;

  p*) # PASTE
    if [ "$MPBTAG" ]
    then
      [ -f "$MPBTAG" ] || usage "tag $MPBTAG not found"
      cat "$MPBTAG"
    else
      pbpaste
    fi
  ;;

  s*) # STORE
    [ "$MPBTAG" ] || usage "missing tag argument"
    pbpaste > "$MPBTAG"
  ;;

  g*) # GIMME
    [ "$MPBTAG" ] || usage "missing tag argument"
    [ -f "$MPBTAG" ] || usage "tag $MPBTAG not found"
    pbcopy < "$MPBTAG"
  ;;

  l*) # LIST
    ls -l
  ;;

  e*) # EDIT
    [ "$EDITOR" ] || EDITOR=/usr/bin/vim
    [ -x "$EDITOR" ] || usage "Unknown editor [$EDITOR], set EDITOR environment variable"
    if [ "$MPBTAG" ]; then # if tag is specified, edit it
      $EDITOR "$MPBTAG"
    else # otherwise just load the buffer
      $EDITOR
    fi
    # Originally I had a pbcopy in here, but that always surprised me
    # when I just wanted to select a part of it. Tricky.
  ;;

  d*) # DELETE
    [ "$MPBTAG" ] || usage "missing tag argument"
    [ -f "$MPBTAG" ] || usage "tag $MPBTAG not found"
    rm -f "$MPBTAG"
  ;;

  *)
    usage
  ;;

esac

